### ISSUE TITLE
Slot synonyms are not used

### ISSUE THREAD

**Issue by NullEnt1ty** [rhasspy/rhasspy-snips-nlu#1]
Snips NLU does not use the synonyms that I defined for my slots.

Example:

Let's assume I have the following room slots:

```
(den | playroom | downstairs):den
(bath | bathroom):bathroom
```

This will translate to the following entity in dataset.yaml:

```yaml
type: entity
name: "room"
values:
  - "den"
  - "playroom"
  - "downstairs"
  - "bath"
  - "bathroom"
```

Snips NLU recognizes the room entity, but when I say "playroom" it outputs "playroom" instead of "den". The good news is that Snips NLU does support [synonyms](https://snips-nlu.readthedocs.io/en/latest/data_model.html#entity-values-synonyms) 🎉

In this case, the entity needs to look like this (untested):

```yaml
type: entity
name: "room"
values:
  - ["den", "playroom", "downstairs"]
  - ["bath", "bathroom"]
```
